defmodule Lux.LLM.ResponseCache do
  @moduledoc """
  GenServer-based caching layer for LLM responses.

  This module provides:

  - Fast ETS-backed lookups for cached responses
  - TTL (time-to-live) expiration for cache entries
  - Configurable maximum cache size with LRU eviction
  - Deterministic cache key generation from requests
  - Cache statistics and monitoring

  ## Usage

      # Start the cache (typically done via supervisor)
      {:ok, _pid} = Lux.LLM.ResponseCache.start_link()

      # Generate a cache key from a request
      key = Lux.LLM.ResponseCache.generate_key(:openai, request)

      # Check cache before making API call
      case Lux.LLM.ResponseCache.get(key) do
        {:ok, cached_response} -> cached_response
        {:error, :not_found} ->
          response = make_api_call(request)
          Lux.LLM.ResponseCache.put(key, response)
          response
      end

  ## Configuration

  The cache can be configured with:

  - `:ttl_ms` - Default TTL for cache entries (default: 1 hour)
  - `:max_size` - Maximum number of cache entries (default: 10,000)
  - `:cleanup_interval_ms` - Interval for cleanup tasks (default: 60 seconds)
  - `:name` - Name for the GenServer (default: `Lux.LLM.ResponseCache`)

  """

  use GenServer

  require Logger

  # Default configuration values
  @default_ttl_ms ::timer.hours(1)
  @default_max_size 10_000
  @default_cleanup_interval_ms ::timer.seconds(60)

  # ETS table names
  @cache_table :lux_llm_response_cache
  @meta_table :lux_llm_response_cache_meta

  # === Types ===

  @type cache_key :: binary()
  @type cache_entry :: %{
          value: term(),
          expires_at: integer(),
          inserted_at: integer(),
          last_accessed_at: integer(),
          access_count: non_neg_integer()
        }

  @type cache_stats :: %{
          size: non_neg_integer(),
          hits: non_neg_integer(),
          misses: non_neg_integer(),
          evictions: non_neg_integer(),
          expirations: non_neg_integer()
        }

  @type option ::
          {:ttl_ms, pos_integer()}
          | {:max_size, pos_integer()}
          | {:cleanup_interval_ms, pos_integer()}
          | {:name, atom()}

  # === PUbI@ AP I ===

  @doc """
  Starts the response cache GenServer.

  ## Options

  - `:ttl_ms` - Default TTL for cache entries (default: 1 hour)
  - `:max_size` - Maximum number of cache entries (default: 10,000)
  - `:cleanup_interval_ms` - Interval for cleanup tasks (default: 60 seconds)
  - `:name` - Name for the GenServer (default: `Lux.LLM.ResponseCache`)

  ## Examples

      iex> Lux.LLM.ResponseCache.start_link()
      {:ok, #PID<0.123.0>}

      iex> Lux.LLM.ResponseCache.start_link(ttl_ms: 300_000, max_size: 1_000)
      {:ok, #PID<0.124.0>}

  """
  @spec start_link([option()]) :: GenServer.on_start()
  def start_link(opts \\ []) do
    name = Keyword.get(opts, :name, __MODULE__)
    GenServer.start_link(__MODULE__, opts, name: name)
  end

  @doc """
  Generates a deterministic cache key from a provider and request.

  The key is generated by hashing the canonicalized request data,
  ensuring that identical requests produce identical keys.

  ## Examples

      iex> request = %{messages: [%{role: :user, content: "Hello"}], model: "gpt-4"}
      iex> Lux.LLM.ResponseCache.generate_key(:openai, request)
      "a1b2c3d4e5f6..."

  """
  @spec generate_key(atom(), map()) :: cache_key()
  def generate_key(provider, request) when is_atom(provider) and is_map(request) do
    # Canonicalize the request by removing non-deterministic fields
    # and sorting keys for consistent hashing
    canonical_request =
      request
      |> Map.drop([:metadata, :stream])
      |> canonicalize_map()

    data_to_hash = {provider, canonical_request}
    hash = :crypto.hash(:sha256, :erlang.term_to_binary(data_to_hash))
    Base.encode16(hash, case: :lower)
  end

  @doc """
  Retrieves a cached response by key.

  Returns `{:ok, value}` if found and not expired, otherwise `{:error, :not_found}`.

  ## Examples

      iex> Lux.LLM.ResponseCache.get("a1b2c3d4e5f6...")
      {:ok, %completion_response{}}

      iex> Lux.LLM.ResponseCache.get("nonexistent")
      {:error, :not_found}

  """
  @spec get(cache_key(), atom()) :: {:ok, term()} | {:error, :not_found}
  def get(key, server \\ __MODULE__) when is_binary(key) do
    GenServer.call(server, {:get, key})
  end

  @doc """
  Stores a response in the cache.

  ## Options

  - `:ttl_ms` - Custom TTL for this entry (overrides default)

  ## Examples

      iex> Lux.LLM.ResponseCache.put("a1b2c3d4e5f6...", response)
      :ok

      iex> Lux.LLM.ResponseCache.put("a1b2c3d4e5f6...", response, ttl_ms: 300_000)
      :ok

  """
  @spec put(cache_key(), term(), Keyword.t()) :: :ok
  def put(key, value, opts \\ []) when is_binary(key) do
    server = Keyword.get(opts, :server, __MODULE__)
    ttl_ms = Keyword.get(opts, :ttl_ms)
    GenServer.call(server, {:put, key, value, ttl_ms})
  end

  @doc """
  Deletes a specific entry from the cache.

  ## Examples

      iex> Lux.LLM.ResponseCache.delete("a1b2c3d4e5f6...")
      :ok

  """
  @spec delete(cache_key(), atom()) :: :ok
  def delete(key, server \\ __MODULE__) when is_binary(key) do
    GenServer.call(server, {:delete, key})
  end

  @doc """
  Clears all entries from the cache.

  ## Examples

      iex> Lux.LLM.ResponseCache.clear()
      :ok

  """
  @spec clear(atom()) :: :ok
  def clear(server \\ __MODULE__) do
    GenServer.call(server, :clear)
  end

  @doc """
  Returns cache statistics.

  ## Examples

      iex> Lux.LLM.ResponseCache.stats()
      {:ok, %{size: 100, hits: 500, misses: 100, evictions: 10, expirations: 5}}

  """
  @spec stats(atom()) :: {:ok, cache_stats()}
  def stats(server \\ __MODULE__) do
    GenServer.call(server, :stats)
  end

  @doc """
  Returns the current number of entries in the cache.

  ## Examples

      iex> Lux.LLM.ResponseCache.size()
      100

  """
  @spec size(atom()) :: non_neg_integer()
  def size(server \\ __MODULE__) do
    GenServer.call(server, :size)
  end

  # === GenServer Callbacks ===

  @impl true
  def init(opts) do
    ttl_ms = Keyword.get(opts, :ttl_ms, @default_ttl_ms)
    max_size = Keyword.get(opts, :max_size, @default_max_size)
    cleanup_interval_ms = Keyword.get(opts, :cleanup_interval_ms, @default_cleanup_interval_ms)

    # Create ETS tables
    cache_table = :ets.new(@cache_table, [:set, :public, :named_table, read_concurrency: true])
    meta_table = :ets.new(@meta_table, [:set, :public, :named_table])

    # Initialize stats
    :ets.insert(meta_table, {:hits, 0})
    :ets.insert(meta_table, {:misses, 0})
    :ets.insert(meta_table, {:evictions, 0})
    :ets.insert(meta_table, {:expirations, 0})

    # Schedule periodic cleanup
    schedule_cleanup(cleanup_interval_ms)

    state = %{
      cache_table: cache_table,
      meta_table: meta_table,
      ttl_ms: ttl_ms,
      max_size: max_size,
      cleanup_interval_ms: cleanup_interval_ms
    }

    Logger.info("ResponseCache started with ttl_ms=#{ttl_ms}, max_size=#{max_size}")

    {:ok, state}
  end

  @impl true
  def handle_call({:get, key}, _from, state) do
    result = do_get(key, state)
    {:reply, result, state}
  end

  @impl true
  def handle_call({:put, key, value, custom_ttl}, _from, state) do
    do_put(key, value, custom_ttl, state)
    {:reply, :ok, state}
  end

  @impl true
  def handle_call({:delete, key}, _from, state) do
    :ets.delete(state.cache_table, key)
    {:reply, :ok, state}
  end

  @impl true
  def handle_call(:clear, _from, state) do
    :ets.delete_all_objects(state.cache_table)
    {:reply, :ok, state}
  end

  @impl true
  def handle_call(:stats, _from, state) do
    stats = get_stats(state)
    {:reply, {:ok, stats}, state}
  end

  @impl true
  def handle_call(:size, _from, state) do
    size = :ets.info(state.cache_table, :size)
    {:reply, size, state}
  end

  @impl true
  def handle_info(:cleanup, state) do
    do_cleanup(state)
    schedule_cleanup(state.cleanup_interval_ms)
    {:noreply, state}
  end

  @impl true
  def handle_info(_msg, state) do
    {:noreply, state}
  end

  @impl true
  def terminate(_reason, state) do
    :ets.delete(state.cache_table)
    :ets.delete(state.meta_table)
    :ok
  end

  # === Private Functions ===

  defp do_get(key, state) do
    now = System.system_time(:millisecond)

    case :ets.lookup(state.cache_table, key) do
      [{^ke{, entry}] ->
        if entry.expires_at > now do
          # Update access metadata
          updated_entry = %{
            entry
            | last_accessed_at: now,
              access_count: entry.access_count + 1
          }

          :ets.insert(state.cache_table, {key, updated_entry})
          increment_stat(state.meta_table, :hits)
          {:ok, entry.value}
        else
          # Expired - delete and return not found
          :ets.delete(state.cache_table, key)
          increment_stat(state.meta_table, :misses)
          increment_stat(state.meta_table, :expirations)
          {:error, :not_found}
        end

      [] ->
        increment_stat(state.meta_table, :misses)
        {:error, :not_found}
    end
  end

  defp do_put(key, value, custom_ttl, state) do
    now = System.system_time(:millisecond)
    ttl_ms = custom_ttl || state.ttl_ms

    entry = %{
      value: value,
      expires_at: now + ttl_ms,
      inserted_at: now,
      last_accessed_at: now,
      access_count: 0
    }

    # Check if we need to evict before inserting
    current_size = :ets.info(state.cache_table, :size)

    if current_size >= state.max_size do
      evict_lru(state)
    end

    :ets.insert(state.cache_table, {key, entry})
  end

  defp evict_lru(state) do
    # Find the least recently used entry
    # We iterate through all entries and find the one with the oldest last_accessed_at
    lru_key =
      :ets.foldl(
        fn {key, entry}, acc ->
          case acc do
            nil ->
              {key, entry.last_accessed_at}

            {_old_key, old_time} ->
              if entry.last_accessed_at < old_time do
                {key, entry.last_accessed_at}
              else
                acc
              end
          end
        end,
        nil,
        state.cache_table
      )

    case lru_key do
      {key, _time} ->
        :ets.delete(state.cache_table, key)
        increment_stat(state.meta_table, :evictions)

      nil ->
        :ok
    end
  end

  defp do_cleanup(state) do
    now = System.system_time(:millisecond)
    expired_count = Ref.new(0)

    # Find and delete expired entries
    :ets.foldl(
      fn {key, entry}, acc ->
        if entry.expires_at <= now do
          :ets.delete(state.cache_table, key)
          Ref.update(expired_count, &(&1 + 1))
        end

        acc
      end,
      :ok,
      state.cache_table
    )

    count = Ref.read(expired_count)

    if count > 0 do
      :ets.update_counter(state.meta_table, :expirations, count)
      Logger.debug("ResponseCache cleanup: removed #{count} expired entries")
    end
  end

  defp get_stats(state) do
    size = :ets.info(state.cache_table, :size)

    hits =
      case :ets.lookup(state.meta_table, :hits) do
        [{:hits, val}] -> val
        [] -> 0
      end

    misses =
      case :ets.lookup(state.meta_table, :misses) do
        [{:misses, val}] -> val
        [] -> 0
      end

    evictions =
      case :ets.lookup(state.meta_table, :evictions) do
        [{:evictions, val}] -> val
        [] -> 0
      end

    expirations =
      case :ets.lookup(state.meta_table, :expirations) do
        [{:expirations, val}] -> val
        [] -> 0
      end

    %{
      size: size,
      hits: hits,
      misses: misses,
      evictions: evictions,
      expirations: expirations
    }
  end

  defp increment_stat(meta_table, key) do
    :ets.update_counter(meta_table, key, 1)
  end

  defp schedule_cleanup(interval_ms) do
    Process.send_after(self(), :cleanup, interval_ms)
  end

  defp canonicalize_map(map) when is_map(map) do
    map
    |> Enum.map(fn
      {k, v} when is_map(v) -> {k, canonicalize_map(v)}
      {k, v} when is_list(v) -> {k, canonicalize_list(v)}
      {k, v} -> {k, v}
    end)
    |> Enum.sort_by(fn {k, _} -> k end)
  end

  defp canonicalize_list(list) when is_list(list) do
    Enum.map(list, fn
      item when is_map(item) -> canonicalize_map(item)
      item when is_list(item) -> canonicalize_list(item)
      item -> item
    end)
  end
end